language: python
python:
    - "2.7"
install: "pip install -r requirements.txt"
script:
    - "fab deploy"
notifications:
    email: false
    slack:
        rooms:
            - cloock:SXLRwJ3UHzH4R4sZwycCnt9J#lunchbreak-api
branches:
    only:
        - staging
