sudo: required
services:
- mysql
- docker
language: python
cache: pip
python:
- '3.5'
install:
- echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
- wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
- sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
- sudo apt-get update -q
- sudo apt-get install -q -y -o Dpkg::Options::=--force-confnew mysql-server --force-yes
- sudo mysql_upgrade
- pip install -r lunchbreak/requirements-dev.txt --exists-action w
script:
- fab deploy:check_deploy=True
notifications:
  email: false
  slack:
    secure: F/izNrNAiOfPIMVwH53UD3UtTdO+rfR4c2utLRol8axCBy/L6+pEVqo36UZ5kBOYEwfxaGuALMSY621qcziWzqoXoy8ekgCOJWA2sqpMpwIZ9YQvIFLTToIiKBbomgC5KZi4zEazyNdLDHdU4En73nru1DuIRYq81vSg55mKJuA=
