sudo: required
services:
- postgresql
- docker
language: python
cache: pip
python:
- '3.5'
install:
- pip install -r lunchbreak/requirements-dev.txt --exists-action w
script:
- fab deploy:check_deploy=True
notifications:
  email: false
  slack:
    secure: F/izNrNAiOfPIMVwH53UD3UtTdO+rfR4c2utLRol8axCBy/L6+pEVqo36UZ5kBOYEwfxaGuALMSY621qcziWzqoXoy8ekgCOJWA2sqpMpwIZ9YQvIFLTToIiKBbomgC5KZi4zEazyNdLDHdU4En73nru1DuIRYq81vSg55mKJuA=
