language: python
python:
  - "2.7"
install: "pip install -r lunchbreak/requirements-dev.txt --exists-action w"
script:
  - "fab deploy"
notifications:
  email: false
  slack:
    rooms:
      - cloock:SXLRwJ3UHzH4R4sZwycCnt9J#lunchbreak-api
branches:
  only:
    - master
