language: python
python:
    - "2.7"
install: "pip install -r requirements.txt"
before_script:
    - "cp Lunchbreak/settings.py Lunchbreak/settings_backup.py"
    - "sed -i \"s/'USER': 'lunchbreak'/'USER': 'root'/g\" Lunchbreak/settings.py"
    - "sed -i \"s/'PASSWORD': 'lunchbreak'/'PASSWORD': ''/g\" Lunchbreak/settings.py"
script: "python manage.py test lunch"
after_script:
    - "fab deploy"
    - "mv Lunchbreak/settings_backup.py Lunchbreak/settings.py"
notifications:
    email: false
    slack:
        rooms:
            - cloock:SXLRwJ3UHzH4R4sZwycCnt9J#lunchbreak-api
branches:
    only:
        - staging
