language: python
python:
    - "2.7"
install: "pip install -r requirements.txt"
before_script:
    - mysqluserclone --source=root@localhost --destination=root@localhost lunchbreak:lunchbreak@localhost
script: "python manage.py test"
notifications:
    email: false
    slack:
        rooms:
            - cloock:SXLRwJ3UHzH4R4sZwycCnt9J#lunchbreak-api
