sudo: required
services:
  - mysql
  - docker
language: python
python:
  - '3.5'
# Have to install MySQL: https://github.com/travis-ci/travis-ci/issues/4870
install:
  # MySQL 5.7 installation
  - echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
  - wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
  - sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y -o Dpkg::Options::=--force-confnew mysql-server
  - sudo mysql_upgrade
  # Lunchbreak requirements
  - pip install -r lunchbreak/requirements-dev.txt --exists-action w
script:
  - fab test
notifications:
  email: false
  slack:
    rooms:
      - cloock:SXLRwJ3UHzH4R4sZwycCnt9J#lunchbreak-backend
deploy:
    provider: script
    script: 'fab deploy:skiptests=True,check_deploy=True'
    on:
      all_branches: true
      tags: true
      repo: AndreasBackx/Lunchbreak-Backend
