version: '2'
services:
  lunchbreak:
    image: 'andreasbackx/lunchbreak:latest'
    container_name: lunchbreak
    restart: always
    expose:
      - '49152'
    env_file:
      - ./base.env
    volumes:
      - ./lunchbreak/keys/apns:/etc/lunchbreak/certificates/apns:ro
