version: '2'
services:
  nginx:
    volumes:
      - /var/lunchbreak/staging/static:/var/lunchbreak/static:ro
  lunchbreak_staging:
    image: 'andreasbackx/lunchbreak:latest'
    container_name: lunchbreak_staging
    restart: always
    links:
      - db
    expose:
      - '49152'
    env_file:
      - ./base.env
      - ./staging.env
    depends_on:
      - db
    volumes:
      - ./docker/web/keys/apns:/etc/lunchbreak/certificates/apns:ro
      - ./docker/web/secrets/staging:/var/secrets:ro
      - /var/lunchbreak/staging/static:/var/lunchbreak/static:rw
      - /var/lunchbreak/staging/media:/var/lunchbreak/media:rw
      - /var/lunchbreak/staging/media-private:/var/lunchbreak/media-private:rw
