version: '2'

services:
  nginx:
    volumes:
      - /var/lunchbreak/production/static:/var/lunchbreak_production/static:ro
      - /var/lunchbreak/production/media:/var/lunchbreak_production/media:ro
      - /var/lunchbreak/production/media-private:/var/lunchbreak_production/media-private:ro
      - /var/lunchbreak/staging/static:/var/lunchbreak_staging/static:ro
      - /var/lunchbreak/staging/media:/var/lunchbreak_staging/media:ro
      - /var/lunchbreak/staging/media-private:/var/lunchbreak_staging/media-private:ro
      - /var/lunchbreak/development/static:/var/lunchbreak_development/static:ro
      - /var/lunchbreak/development/media:/var/lunchbreak_development/media:ro
      - /var/lunchbreak/development/media-private:/var/lunchbreak_development/media-private:ro

  lunchbreak_production:
    extends:
      file: common-services.yml
      service: lunchbreak
    image: 'andreasbackx/lunchbreak:production'
    container_name: lunchbreak_production
    links:
      - rabbitmq
    depends_on:
      - nginx
      - rabbitmq
    env_file:
      - ./production.env
    volumes:
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock:ro
      - ./lunchbreak/secrets/production:/var/secrets:ro
      - /var/lunchbreak/production/log:/var/lunchbreak/log:rw
      - /var/lunchbreak/production/static:/var/lunchbreak/static:rw
      - /var/lunchbreak/production/media:/var/lunchbreak/media:rw
      - /var/lunchbreak/production/media-private:/var/lunchbreak/media-private:rw
    network_mode: bridge

  lunchbreak_staging:
    extends:
      file: common-services.yml
      service: lunchbreak
    # TODO Change this tag to staging when first deploying to staging
    image: 'andreasbackx/lunchbreak:staging'
    container_name: lunchbreak_staging
    links:
      - rabbitmq
    depends_on:
      - nginx
      - rabbitmq
    env_file:
      - ./staging.env
    volumes:
      - /var/run/postgresql:/var/run/postgresql:ro
      - ./lunchbreak/secrets/staging:/var/secrets:ro
      - /var/lunchbreak/staging/log:/var/lunchbreak/log:rw
      - /var/lunchbreak/staging/static:/var/lunchbreak/static:rw
      - /var/lunchbreak/staging/media:/var/lunchbreak/media:rw
      - /var/lunchbreak/staging/media-private:/var/lunchbreak/media-private:rw
    network_mode: bridge

  lunchbreak_development:
    extends:
      file: common-services.yml
      service: lunchbreak
    image: 'andreasbackx/lunchbreak:development'
    container_name: lunchbreak_development
    links:
      - rabbitmq
    depends_on:
      - nginx
      - rabbitmq
    env_file:
      - ./development.env
    volumes:
      - /var/run/postgresql:/var/run/postgresql:ro
      - ./lunchbreak/secrets/development:/var/secrets:ro
      - /var/lunchbreak/development/log:/var/lunchbreak/log:rw
      - /var/lunchbreak/development/static:/var/lunchbreak/static:rw
      - /var/lunchbreak/development/media:/var/lunchbreak/media:rw
      - /var/lunchbreak/development/media-private:/var/lunchbreak/media-private:rw
    network_mode: bridge
