version: '2'
services:
  db:
    image: mysql:5.7.15
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql:/var/lib/mysql
    expose:
      - '3306'
    ports:
      - '3306:3306'
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    restart: always
    # Dummy port for bug reported here: https://github.com/jwilder/nginx-proxy/issues/438
    expose:
      - '1234'
    volumes_from:
      - nginx
    volumes:
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    volumes_from:
      - nginx
    volumes:
      - ./nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
  rabbitmq:
    image: rabbitmq:3.6.6
    container_name: rabbitmq
    # RabbitMQ stores data based on the hostname so this should remain the same
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=lunchbreak
      - RABBITMQ_DEFAULT_PASS=lunchbreak
    ports:
      - '5672'
    volumes:
      - /var/lib/rabbitmq

volumes:
  mysql:
